mission2/Models/CalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mission2.Models
{
    public class CalcModel
    {
        [Required (ErrorMessage = "Please enter the scores for assignments")]
        [Range(1, 100)]
        public float assign { get; set; }

        [Required(ErrorMessage = "Please enter the scores for projects")]
        [Range(1, 100)]
        public float grp_proj { get; set; }

        [Required(ErrorMessage = "Please enter the scores for quizzes")]
        [Range(1, 100)]
        public float quiz { get; set; }

        [Required(ErrorMessage = "Please enter the scores for exams")]
        [Range(1, 100)]
        public float exam { get; set; }

        [Required(ErrorMessage = "Please enter the scores for intex")]
        [Range(1, 100)]
        public float inte { get; set; }

    }
}

mission2/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mission2.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace mission2.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculator(CalcModel model)
        {
            return View();
        }

    }
}

mission2/Views/Blah/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model CalcModel;


<h2>Grade Calculator:</h2>
<h6>(Enter the grade percentage for each category (rounded to the nearest tenth, i.e. 76.5 or 90.0)</h6>

<form>
    <label>Assignments:</label>
    <input id="assignment" asp-for="assign" />
    <br />
    <label>Group Project:</label>
    <input id="grp_project" asp-for="grp_proj" />
    <br />
    <label>Quizzes:</label>
    <input id="quizzes" asp-for="quiz" v/>
    <br />
    <label>Exams:</label>
    <input id="exams" asp-for="exam" />
    <br />
    <label>INTEX:</label>
    <input id="intex" asp-for="inte" />
    <br />
    <input id="calc_button" type="submit" value="Calculate" />

    <div asp-validation-summary="All"></div>
</form>

mission2/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}

<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>What I Want to Get Out of IS 413</h2>
                <p class="lead">
                    I think I want to get out of this class similar to what I got out of IS 403: Be able to create and deploy a
                    website from start to finish. I don't know the plan for the end of the class,
                    but I'd like to learn how to deploy using a different tool than Heroku. I'm not expecting to be an ASP.NET pro by any means, but
                    I'm hoping that I'll feel confident about putting ASP.NET as a skill on my resume after this class.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>Top 3 IS Jobs</h2>
                <p class="lead">
                    <ul>
                        <li>Data Science</li>
                        <li>Cybersecurity</li>
                        <li>Software Development</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</section>

mission2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" href="~/img/thumbs_up.jpeg" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/styles.css" rel="stylesheet" />
    <link href="~/css/myStyles.css" rel="stylesheet" />
    <link rel="icon" href="~/img/favicon.ico" />

</head>

<body>

    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-controller="Blah" asp-action="Index">Parker Schmidt</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <a asp-controller="Blah" asp-action="Index">Home</a>
            <a asp-controller="Blah" asp-action="Calculator">Grade Calculator</a>
        </div>
    </nav>

    <!-- Header - set the background image for the header in the line below-->
    <header class="py-5 bg-image-full">
        <div class="text-center my-5">
            <img class="img-fluid rounded-circle mb-4 main-photo" src="~/img/parker.png" />
        </div>
    </header>


    <div>
        @RenderBody()
    </div>

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Parker Schmidt 2022</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/js/calculator.js"></script>

</body>

</html>